In [2]:
import numpy as np

In [3]:
 #reshape of arrays
arr1 = np.array([[2,3,4],[5,6,7],[8,9,23],[7,3,5]])
print(arr1)
arr1 = arr1.reshape(3,4)
print(arr1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 23]
 [ 7  3  5]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [23  7  3  5]]


In [4]:
arr3= np.arange(10,15)
print(arr3)
arr3.resize(8,4)
print(arr3)
arr3.resize(6,)
arr3

[10 11 12 13 14]
[[10 11 12 13]
 [14  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]]


array([10, 11, 12, 13, 14,  0])

In [7]:
#cannot resize an array that references
arr3= np.arange(10,15)
print(arr3)
arr4 = arr3
print(arr4)
arr4.resize(6,)
arr4

[10 11 12 13 14]
[10 11 12 13 14]


ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

In [6]:
arr3= np.arange(10,15)
arr4 = np.resize(arr3,(5,2))
print(arr3)
arr4

[10 11 12 13 14]


array([[10, 11],
       [12, 13],
       [14, 10],
       [11, 12],
       [13, 14]])

In [7]:
#np.ravel

arr5 = np.array([np.arange(15,24),np.arange(67,76)])
print(arr5)
arr5.ravel()

[[15 16 17 18 19 20 21 22 23]
 [67 68 69 70 71 72 73 74 75]]


array([15, 16, 17, 18, 19, 20, 21, 22, 23, 67, 68, 69, 70, 71, 72, 73, 74,
       75])

In [10]:
arr5 = np.array([np.arange(15,24),np.arange(67,76)])
print(arr5)
arr5.flatten()

[[15 16 17 18 19 20 21 22 23]
 [67 68 69 70 71 72 73 74 75]]


array([15, 16, 17, 18, 19, 20, 21, 22, 23, 67, 68, 69, 70, 71, 72, 73, 74,
       75])

In [24]:
arr5 = np.array(np.arange(15,24))
print(arr5.shape)
print(arr5)
arr5 = arr5[:,np.newaxis]
print(arr5)
arr5.shape

(9,)
[15 16 17 18 19 20 21 22 23]
[[15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


(9, 1)

In [25]:
#adding new dimension
arr5 = np.array([np.arange(15,24),np.arange(67,76)])
arr5.shape
arr5 = arr5[:,np.newaxis]
print(arr5)
arr5.shape

[[[15 16 17 18 19 20 21 22 23]]

 [[67 68 69 70 71 72 73 74 75]]]


(2, 1, 9)

In [8]:
arr5 = np.array([[4,8,1],[5,2,7]])
print(arr5)
arr5.sort(axis=1)
print(arr5)
arr5.sort(axis=0)
print(arr5)

[[4 8 1]
 [5 2 7]]
[[1 4 8]
 [2 5 7]]
[[1 4 7]
 [2 5 8]]


In [41]:
#Reduction and statistical operation
arr5 = np.array([[4,8,1],[5,2,7]])
print(arr5)
arr5.prod()

[[4 8 1]
 [5 2 7]]


2240

In [45]:
print(arr5)
print(np.prod(arr5,axis = 0))
print(np.prod(arr5,axis = 1))

[[4 8 1]
 [5 2 7]]
[20 16  7]
[32 70]


In [47]:
np.sum(arr5)

27

In [ ]:
# Case study
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(12)

# Initialize all_walks
all_walks=[]

# Simulate random walk 10 times
for i in range(10) :

    # Code from before
    random_walk = [0]
    
    for x in range(100) :
        step = random_walk[-1]
        dice = np.random.randint(1,7)
        #print(dice)
        if dice <= 2:
            step = max(0, step - 1)
        elif dice <= 5:
            step = step + 1
        else:
            step = step + np.random.randint(1,7)
            
        #implement clumsiness
        if np.random.rand() <= 0.001:
            step = 0 
            
        #print(dice,step)
        random_walk.append(step)
    
    # Append random_walk to all_walks
    all_walks.append(random_walk)

# Print all_walks
print(all_walks)
plt.plot(all_walks)
plt.show()

# Pandas

In [97]:
import pandas as pd
import numpy as np

In [100]:
#creating series using numpy array

series1  = pd.Series(np.random.rand(4))
series1

0    0.129941
1    0.105481
2    0.590363
3    0.376655
dtype: float64

In [102]:
series1.index

RangeIndex(start=0, stop=4, step=1)

In [107]:
series1  = pd.Series(np.random.rand(4),index=[12,13,14,15])
print(series1)
series1[12]

12    0.529873
13    0.014475
14    0.982928
15    0.889686
dtype: float64


0.5298732477894789

In [110]:
#calendar

import calendar as cal
mon = [cal.month_name[i] for i in np.arange(7,13)]
year = pd.Series(np.arange(7,13),index = mon)
year

July          7
August        8
September     9
October      10
November     11
December     12
dtype: int32

In [114]:
print(year.index)
year['October']

Index(['July', 'August', 'September', 'October', 'November', 'December'], dtype='object')


10

In [117]:
#creating series from dictionary

dict1 = {'France':'Euro','India':'Rupee','Japan':'Yen','UK':'Pound'}
print(dict1)
pd.Series(dict1)

{'France': 'Euro', 'India': 'Rupee', 'Japan': 'Yen', 'UK': 'Pound'}


France     Euro
India     Rupee
Japan       Yen
UK        Pound
dtype: object

In [120]:
dict1 = {'France':'Euro','India':'Rupee','Japan':'Yen','UK':'Pound'}
print(dict1)
pd.Series(dict1 ,index = ['UK','Japan','France','India'])

{'France': 'Euro', 'India': 'Rupee', 'Japan': 'Yen', 'UK': 'Pound'}


UK        Pound
Japan       Yen
France     Euro
India     Rupee
dtype: object

In [122]:
#creating series using scalar value

pd.Series('Dendrobium',index = ['name','speciesname','country'])

name           Dendrobium
speciesname    Dendrobium
country        Dendrobium
dtype: object