In [2]:
import numpy as np
## 1-dimensional array

array_1 = np.array([11,22,33])   # creating a single array with homogeneous datatype (only integer)
array_1

array([11, 22, 33])

In [4]:
## 2-dimensional array

array_2 = np.array([[11,22,33],[21,22,23]])  # creating a 2 dimensional array with homogeneous datatype
array_2

array([[11, 22, 33],
       [21, 22, 23]])

In [5]:
##shape of array

array_2.shape

(2, 3)

In [6]:
array_2.ndim   # .ndim -> gives the dimensions of an array

2

In [7]:
## creating array using arange function ->np.arange

array_3 = np.arange(5)
array_3

array([0, 1, 2, 3, 4])

In [8]:
## creating array with start index and stop index using arange function ->np.arange

array_3 = np.arange(5,10)
array_3

array([5, 6, 7, 8, 9])

In [9]:
array_4 = np.arange(5,20,5)  #here np.arange(start index,stop index,step value)
array_4

array([ 5, 10, 15])

In [10]:
## np.linspace -> creates linearly space events ie.,the difference between the numbers are the same.

array_5 = np.linspace(0,1,10)
array_5

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [11]:
## np.ones

array_55 = np.ones((2,3))  # creates an 2x3 array with ones.
array_55

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
## np.zeros

array_6 = np.zeros((5,3))  # creates an 5x3 array with ones.
array_6

In [ ]:
## np.eye   - > creates a identity matrix - equal number of rows and columns

array_7 = np.eye(5)  # creates an identical array.
array_7

In [ ]:
## np.diag -> used to populate or change the diagnol elements of an array.

array_8 = np.diag((1,2,3,4))  # creates an identical array.
array_8


In [ ]:
## np.rand -> creates random variables across the range

array_88 = np.random.rand(4)
array_88

In [3]:
array_882 = np.random.rand(4,2)
array_882

array([[0.34134567, 0.73625696],
       [0.67023264, 0.27181679],
       [0.7398672 , 0.26102356],
       [0.88859973, 0.4285583 ]])

In [ ]:
array_9 = np.random.randn(5)
array_9

In [4]:
# to generate random numbers within a range
np.random.seed(50)   
# .seed(any number) to get the same random variable. Cos we have set a seed as 50 which is a random number.
arr_1 = np.random.randint(1,100,5)
arr_1

array([49, 97, 12, 34, 95])

In [ ]:
arr_1[arr_even] # to display the even numbers in array _1

In [ ]:
# '?function name' -> to get help regarding a specific function 
#  eg., ?np.random.randn

?np.random.randn

In [ ]:
## np.empty -> used to initialise an array ie., just a structure

array_10 = np.empty((4,3))
array_10

In [ ]:
## np.tile  -> 
array_11 = np.tile(np.array([[5,3],[8,9]]),3)
array_11

# Data Types

In [ ]:
import numpy as np
arr_1 = np.array([4,-2,5,9],dtype=float)
arr_1

In [ ]:
type(arr_1)

In [ ]:
arr_1.dtype   # dtype is used to find the type of array

In [ ]:
# defalt data type
arr_1 = np.array([4,-2,5,9])
arr_1.dtype

In [ ]:
arr_4 = np.array(['hello','hi','welcome'])
arr_4.dtype

In [ ]:
arr_5 = np.array([True,False])
arr_5.dtype

In [5]:
## Typecasting -> convert one data type to the other

arr_1 = np.array([1,-4,5,6.32])
arr_1.dtype

dtype('float64')

In [6]:
arr_1 = arr_1.astype(int)   # type casting arr_1 from float to int
arr_1.dtype

dtype('int32')

In [7]:
## Numpy Indexing and slicing   - index starts from '0'

arr_1 = np.arange(6)
arr_1


array([0, 1, 2, 3, 4, 5])

In [ ]:
# To access the '0'th element
arr_1[0]

In [ ]:
# accesing the last element

arr_1[-1] 

In [ ]:
# to reverse an array

arr_1[::-1]

# Multi dimensional array

In [10]:
arr_2 = np.array([[4,3],[3,5],[1,2]])
arr_2

array([[4, 3],
       [3, 5],
       [1, 2]])

In [15]:
# to access the elements in the above array

arr_2[2,1]

2

In [ ]:
# to modify the existing value 

arr_2[2,1] = -3
arr_2

In [ ]:
# to retrive the first row ( not the zero th)

arr_2[1]

In [ ]:
# retreive the secong row and all columns

arr_2[2,:]     # the first element ie., before ',' denote the row and the later denotes the columns. in this case its all.

In [9]:
# retrive  columns
# array[row:column]
# accesses all rows and the first column
arr_2[:,1]   

# anything after the ',' refer to the column

NameError: name 'arr_2' is not defined

In [ ]:
arr_1 = np.arange(6)
arr_1

In [ ]:
arr_1[6]  # If elements outside the index are mentioned it throws an error 

In [8]:
arr_5 = 2 * np.arange(10)
arr_5

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr_5[0:6:2]   #arr[start index: end index : step value]
# refers to the elements with the index from 0 to 5 with an increment of 2

In [ ]:
# access the elements with index value from 0 to 2 

arr_5[:3]

In [ ]:
# access the elements with index value from 3 to last 

arr_5[3:]

In [ ]:
#
arr_5[::3]

In [ ]:
# combine both slicing and assignment operation

arr_5[1] = -2
arr_5

In [ ]:
# all elements till index 3 will be assigned as -2 and the rest will remain the same.

arr_5[:3] = -2 
arr_5

In [ ]:
arr_5[2:] = np.ones(8)
arr_5

In [16]:
# Create 5 x 5 array

arr_12 = np.array([[1,2,3,4,5],[11,12,13,14,15],[21,22,23,24,25],[31,32,33,34,35],[41,42,43,44,45]])
arr_12

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45]])

In [20]:
arr_12[0,3:5]

array([4, 5])

In [ ]:
w = arr_12[3:,4:]
w

In [ ]:
arr_12[:,2] # accessing column 2

In [21]:
arr_12[2::2,::2]

array([[21, 23, 25],
       [41, 43, 45]])

In [ ]:
# Filtering 

import

In [ ]:
arr_even = (arr_1 % 2 == 0)   # to check if the elements in the array are even
arr_even

In [ ]:
arr_country = np.array(['India','Switzerland','Italy','','France'])

In [ ]:
# to mask the missing data

arr_country [arr_country == ''] = 'Netherlandsfytf'
arr_country

In [22]:
arr_1

array([0, 1, 2, 3, 4, 5])

In [23]:
# To access specific index in the list

arr_1[[1,2,3]]

array([1, 2, 3])

In [24]:
arr_1[[1,4]] = 100  # assigning the value 100 to the index value 1 and 4
arr_1

array([  0, 100,   2,   3, 100,   5])

In [ ]:
# Complex indexing

arr_15 = np.arange(20)
arr_15

In [27]:
arr_15=np.arange(-11,-20,-1)[::-1]
arr_15

array([-19, -18, -17, -16, -15, -14, -13, -12, -11])

In [31]:
arr_16=0
arr_15[:6] = arr_16
arr_15

array([  0,   0,   0,   0,   0,   0, -13, -12, -11])

# Copy and view

In [5]:
# Copies and views
import numpy as np

arr_1 = np.arange(5)
arr_10

array([0, 1, 2, 3, 4])

In [6]:
arr_2 = arr_1[::2]  # arr_2 is referencing arr_1.If arr_1 is modified then arr_2 will also change
arr_2

array([0, 2, 4])

In [8]:
arr_2[1] = -4
arr_2

array([ 0, -4,  4])

In [9]:
arr_1

array([ 0,  1, -4,  3,  4])

In [32]:
arr_3 = np.arange(10)
arr_3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr_4=arr_3[:3].copy()
arr_4

array([0, 1, 2])

In [34]:
arr_4[1] = -4
arr_3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Basic Operations

In [14]:
import numpy as np

arr_1 = np.arange(1,10) *4  # Multiplication
arr_1

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

In [15]:
arr_2 = np.arange(1,10)**4
arr_2

array([   1,   16,   81,  256,  625, 1296, 2401, 4096, 6561], dtype=int32)

In [16]:
arr_3 = arr_1 * 0.5
arr_3

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [17]:
arr_4 = 3 + np.arange(0,20,2)   # Addition
arr_4

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [18]:
arr_5 = np.arange(10)
arr_5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr_6 = arr_4 - arr_5   # subtraction
arr_6

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
arr_7 = arr_4 * arr_5
arr_7

array([  0,   5,  14,  27,  44,  65,  90, 119, 152, 189])

In [22]:
arr_11 = np.arange(100)
%timeit arr_11 * 3

1.61 µs ± 9.05 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [35]:
arr_12 = range(100)
%timeit [arr_12[i]* 3 for i in arr_12]

26.9 µs ± 9.05 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [27]:
# Matrix multiplication

arr_21 = np.array([[5,2],[6,3]])
arr_22 = np.array([[2,3],[4,5]])
arr_23 = arr_21.dot(arr_22)
arr_23

array([[18, 25],
       [24, 33]])

# Comparison in logical operators

In [29]:
arr_4

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [30]:
arr_5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr_35 = arr_5 < arr_4
arr_35

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [35]:
# Logical operator

arr_17 = np.array([True,False,True,False])
arr_18 = np.array([True,True,False,False])

arr_20 = np.logical_and(arr_17,arr_18)
arr_20

array([ True, False, False, False])

In [37]:
arr_21 = np.array([np.pi,np.pi/2])
arr_21

array([3.14159265, 1.57079633])

In [38]:
arr_25 = np.sin(arr_21)
arr_25

array([1.2246468e-16, 1.0000000e+00])

In [39]:
arr_31 = np.arange(1,6)   # two arrays have different shapes, hence error
arr_32 = np.arange(1,8)
arr_33 = arr_31 + arr_32

ValueError: operands could not be broadcast together with shapes (5,) (7,) 

In [40]:
arr_41 = np.arange(1,7)  # two arrays have same shape, hence true
arr_42 = np.array([1,2,3,4,5,6])
arr_43 = np.array_equal(arr_41,arr_42)
arr_43

True

In [41]:
arr_44 = np.arange(1,10)   # Elements and shapes are equal
arr_45 = np.array([1,2,3,4,5,6,7,8,9])
arr_46 = np.array_equal(arr_44,arr_45) 
arr_46

True

In [42]:
arr_44 = np.arange(1,10)   # shapes are equal but elements are not equal   
arr_45 = np.array([1,2,3,5,5,6,7,8,9])
arr_46 = np.array_equal(arr_44,arr_45) 
arr_46

False

In [50]:
# Comparison for all elements -> turns out to be true only when all elements are equal.

arr_46 = np.all(arr_44 == arr_45)
arr_46

False

In [51]:
# comparison for any elements -> turns out to be true when any elements are equal.
arr_46 = np.any(arr_44 == arr_45)
arr_46

True

# Broadcasting and applying operations

In [86]:
# Broadcasting :- when two arrays are of different shapes than they need to be broadcasted.
# Here the value of arr_2 is applied to arr_1 
# the trailing array of the two arrays should match. eg., arr_1 = 5x4 and arr_2 = 1x4  --> 5 x 4  
# in broadcasting smaller array gets transformed to larger array.
import numpy as np
arr_1 = np.ones([1,3])
arr_1

array([[1., 1., 1.]])

In [81]:
arr_2 = np.ones([3,3])
arr_2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [87]:
arr_3 = arr_1 + arr_2
arr_3

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [56]:
arr_4 = np.array([[11,22,33]])
arr_5 = arr_4.T   # transpose - converts columns into rows
arr_5

array([[11],
       [22],
       [33]])

In [57]:
arr_6 = arr_4 + arr_5
arr_6      # (11+11) (22+11) (33+11)
           # (11+22) (22+22) (33+22)
           # (11+33) (22+33) (33+33)

array([[22, 33, 44],
       [33, 44, 55],
       [44, 55, 66]])

In [59]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [60]:
xx = x.reshape(4,1)
xx

array([[0],
       [1],
       [2],
       [3]])

In [ ]:
y = np.ones(5)